/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mogtrade Economy
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import {
  GetWalletInfoResponseContent
} from '../../../../mogt`rade/schemas/economy';
import type {
  GetWalletInfoResponseContentOutput,
  WalletType
} from '../../../../mogt`rade/schemas/economy';

import {
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpHeaders
} from '@angular/common/http';

import {
  map
} from 'rxjs';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable()
export class EconomyService {
  private readonly http = inject(HttpClient);
 getWalletInfo(type: WalletType, options?: HttpClientBodyOptions): Observable<GetWalletInfoResponseContentOutput>;
 getWalletInfo(type: WalletType, options?: HttpClientEventOptions): Observable<HttpEvent<GetWalletInfoResponseContentOutput>>;
 getWalletInfo(type: WalletType, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<GetWalletInfoResponseContentOutput>>;
  getWalletInfo(
    type: WalletType, options?: HttpClientObserveOptions): Observable<GetWalletInfoResponseContentOutput | HttpEvent<GetWalletInfoResponseContentOutput> | AngularHttpResponse<GetWalletInfoResponseContentOutput>> {
    if (options?.observe === 'events') {
      return this.http.get<GetWalletInfoResponseContentOutput>(
      `/api/v1/wallet/${type}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: GetWalletInfoResponseContent.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<GetWalletInfoResponseContentOutput>(
      `/api/v1/wallet/${type}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    ).pipe(map(response => response.clone({ body: GetWalletInfoResponseContent.parse(response.body) })));
    }

    return this.http.get<GetWalletInfoResponseContentOutput>(
      `/api/v1/wallet/${type}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    ).pipe(map(data => GetWalletInfoResponseContent.parse(data)));
  }
};

export type GetWalletInfoClientResult = NonNullable<GetWalletInfoResponseContentOutput>
