/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const CheckEmailAvailableResponseContent = zod.object({
  "available": zod.boolean().describe('Whether the requested resource identifier is available or not')
})

export type CheckEmailAvailableResponseContent = zod.input<typeof CheckEmailAvailableResponseContent>;
export type CheckEmailAvailableResponseContentOutput = zod.output<typeof CheckEmailAvailableResponseContent>;
