/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const ConflictErrorResponseContent = zod.object({
  "error": zod.string().describe('The error message from the server')
})

export type ConflictErrorResponseContent = zod.input<typeof ConflictErrorResponseContent>;
export type ConflictErrorResponseContentOutput = zod.output<typeof ConflictErrorResponseContent>;
