/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */

export interface CredentialSignInRequestContent {
  /**
     * The user's identifying email address
     * @pattern ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$
     */
  email: string;
  /** The user's password */
  password: string;
}
