/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */

export interface CredentialSignUpRequestContent {
  /** The names of the user */
  names: string;
  /**
     * The email address of the user. MUST be unique
     * @pattern ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$
     */
  email: string;
  /**
     * User password
     * @minLength 6
     * @maxLength 100
     */
  password: string;
  /**
     * Password confirmation. MUST have value equal to the password value
     * @minLength 6
     * @maxLength 100
     */
  confirmPassword: string;
}
