/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const credentialSignInRequestContentEmailRegExp = new RegExp('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$');

export const CredentialSignInRequestContent = zod.object({
  "email": zod.string().regex(credentialSignInRequestContentEmailRegExp).describe('The user\'s identifying email address'),
  "password": zod.string().describe('The user\'s password')
})

export type CredentialSignInRequestContent = zod.input<typeof CredentialSignInRequestContent>;
export type CredentialSignInRequestContentOutput = zod.output<typeof CredentialSignInRequestContent>;
