/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */

export interface CredentialSignInResponseContent {
  /** The access token (JWT) granted to the user */
  accessToken: string;
  /** The refresh token for the client to obtain a new access token on expiration */
  refreshToken: string;
}
