/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const CredentialSignInHeaders = zod.object({
  "X-Device-Id": zod.string().describe('The client device\'s ID')
})

export type CredentialSignInHeaders = zod.input<typeof CredentialSignInHeaders>;
export type CredentialSignInHeadersOutput = zod.output<typeof CredentialSignInHeaders>;
