/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const credentialSignInBodyEmailRegExp = new RegExp('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$');

export const CredentialSignInBody = zod.object({
  "email": zod.string().regex(credentialSignInBodyEmailRegExp).describe('The user\'s identifying email address'),
  "password": zod.string().describe('The user\'s password')
})

export type CredentialSignInBody = zod.input<typeof CredentialSignInBody>;
export type CredentialSignInBodyOutput = zod.output<typeof CredentialSignInBody>;
