/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const InternalServerErrorResponseContent = zod.object({
  "error": zod.string().describe('The error message from the server')
})

export type InternalServerErrorResponseContent = zod.input<typeof InternalServerErrorResponseContent>;
export type InternalServerErrorResponseContentOutput = zod.output<typeof InternalServerErrorResponseContent>;
