/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */

export interface InternalServerErrorResponseContent {
  /** The error message from the server */
  error: string;
}
