/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const RotateAccessTokenResponseContent = zod.object({
  "accessToken": zod.string().describe('The access token (JWT) granted to the user'),
  "refreshToken": zod.string().describe('The refresh token')
})

export type RotateAccessTokenResponseContent = zod.input<typeof RotateAccessTokenResponseContent>;
export type RotateAccessTokenResponseContentOutput = zod.output<typeof RotateAccessTokenResponseContent>;
