/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const RotateAccessTokenHeaders = zod.object({
  "X-Refresh-Token": zod.string(),
  "X-d-Id": zod.string()
})

export type RotateAccessTokenHeaders = zod.input<typeof RotateAccessTokenHeaders>;
export type RotateAccessTokenHeadersOutput = zod.output<typeof RotateAccessTokenHeaders>;
