/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import * as zod from 'zod';

export const UnprocessibleErrorResponseContent = zod.object({
  "error": zod.array(zod.string()).describe('A list of validation messages')
})

export type UnprocessibleErrorResponseContent = zod.input<typeof UnprocessibleErrorResponseContent>;
export type UnprocessibleErrorResponseContentOutput = zod.output<typeof UnprocessibleErrorResponseContent>;
