/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */

export interface UnprocessibleErrorResponseContent {
  /** A list of validation messages */
  error: string[];
}
