/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import {
  CheckEmailAvailableResponseContent,
  CredentialSignInResponseContent,
  RotateAccessTokenResponseContent
} from '../../../schemas/auth';
import type {
  CheckEmailAvailableParams,
  CheckEmailAvailableResponseContentOutput,
  CredentialSignInRequestContent,
  CredentialSignInResponseContentOutput,
  CredentialSignUpRequestContent,
  RotateAccessTokenResponseContentOutput
} from '../../../schemas/auth';

import {
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpHeaders
} from '@angular/common/http';

import {
  map
} from 'rxjs';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value
        .filter(
          (item) =>
            item != null &&
            (typeof item === 'string' ||
              typeof item === 'number' ||
              typeof item === 'boolean' ||
              (item instanceof Date && !Number.isNaN(item.getTime()))),
        )
        .map((item) =>
          item instanceof Date ? item.toISOString() : item,
        ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (value instanceof Date && !Number.isNaN(value.getTime())) {
      // useDates produces Date query params; serialize to ISO so they reach
      // the wire instead of being dropped by the primitive check below. See #3856.
      filteredParams[key] = value.toISOString();
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}





@Injectable()
export class AuthService {
  private readonly http = inject(HttpClient);
/**
 * Check whether an email available for a user
 */
 checkEmailAvailable(params: CheckEmailAvailableParams, options?: HttpClientBodyOptions): Observable<CheckEmailAvailableResponseContentOutput>;
 checkEmailAvailable(params: CheckEmailAvailableParams, options?: HttpClientEventOptions): Observable<HttpEvent<CheckEmailAvailableResponseContentOutput>>;
 checkEmailAvailable(params: CheckEmailAvailableParams, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<CheckEmailAvailableResponseContentOutput>>;
  checkEmailAvailable(
    params: CheckEmailAvailableParams, options?: HttpClientObserveOptions): Observable<CheckEmailAvailableResponseContentOutput | HttpEvent<CheckEmailAvailableResponseContentOutput> | AngularHttpResponse<CheckEmailAvailableResponseContentOutput>> {
    const filteredParams = filterParams({...params, ...options?.params}, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<CheckEmailAvailableResponseContentOutput>(
      `/api/v1/auth/email-available`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,}
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: CheckEmailAvailableResponseContent.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<CheckEmailAvailableResponseContentOutput>(
      `/api/v1/auth/email-available`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,}
    ).pipe(map(response => response.clone({ body: CheckEmailAvailableResponseContent.parse(response.body) })));
    }

    return this.http.get<CheckEmailAvailableResponseContentOutput>(
      `/api/v1/auth/email-available`,{
    ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,}
    ).pipe(map(data => CheckEmailAvailableResponseContent.parse(data)));
  }
/**
 * This endpoint allows legitimate users to obtain a bearer JWT token and a corresponding refresh token
 */
 credentialSignIn(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientBodyOptions): Observable<CredentialSignInResponseContentOutput>;
 credentialSignIn(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientEventOptions): Observable<HttpEvent<CredentialSignInResponseContentOutput>>;
 credentialSignIn(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<CredentialSignInResponseContentOutput>>;
  credentialSignIn(
    credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientObserveOptions): Observable<CredentialSignInResponseContentOutput | HttpEvent<CredentialSignInResponseContentOutput> | AngularHttpResponse<CredentialSignInResponseContentOutput>> {
    if (options?.observe === 'events') {
      return this.http.post<CredentialSignInResponseContentOutput>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: CredentialSignInResponseContent.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.post<CredentialSignInResponseContentOutput>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    ).pipe(map(response => response.clone({ body: CredentialSignInResponseContent.parse(response.body) })));
    }

    return this.http.post<CredentialSignInResponseContentOutput>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    ).pipe(map(data => CredentialSignInResponseContent.parse(data)));
  }
/**
 * Rotate access token
 */
 rotateAccessToken( options?: HttpClientBodyOptions): Observable<RotateAccessTokenResponseContentOutput>;
 rotateAccessToken( options?: HttpClientEventOptions): Observable<HttpEvent<RotateAccessTokenResponseContentOutput>>;
 rotateAccessToken( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<RotateAccessTokenResponseContentOutput>>;
  rotateAccessToken(
     options?: HttpClientObserveOptions): Observable<RotateAccessTokenResponseContentOutput | HttpEvent<RotateAccessTokenResponseContentOutput> | AngularHttpResponse<RotateAccessTokenResponseContentOutput>> {
    if (options?.observe === 'events') {
      return this.http.get<RotateAccessTokenResponseContentOutput>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: RotateAccessTokenResponseContent.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<RotateAccessTokenResponseContentOutput>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    ).pipe(map(response => response.clone({ body: RotateAccessTokenResponseContent.parse(response.body) })));
    }

    return this.http.get<RotateAccessTokenResponseContentOutput>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    ).pipe(map(data => RotateAccessTokenResponseContent.parse(data)));
  }
/**
 * Create user account using credentials
 */
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientBodyOptions): Observable<TData>;
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  credentialSignUp<TData = void>(
    credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }
};

export type CheckEmailAvailableClientResult = NonNullable<CheckEmailAvailableResponseContentOutput>
export type CredentialSignInClientResult = NonNullable<CredentialSignInResponseContentOutput>
export type RotateAccessTokenClientResult = NonNullable<RotateAccessTokenResponseContentOutput>
export type CredentialSignUpClientResult = NonNullable<void>
