/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mogtrade Economy
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const WalletType = zod.enum(['virtual', 'real'])

export type WalletType = zod.input<typeof WalletType>;
export type WalletTypeOutput = zod.output<typeof WalletType>;
