/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mogtrade Economy
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const getWalletInfoResponseContentBalanceRegExp = new RegExp('^[0-9]{0,14}\\.?[0-9]{1,4}$');
export const getWalletInfoResponseContentIdRegExp = new RegExp('^[0-9A-HJKMNP-TV-Z]{26}$');

export const GetWalletInfoResponseContent = zod.object({
  "balance": zod.string().regex(getWalletInfoResponseContentBalanceRegExp).optional(),
  "id": zod.string().regex(getWalletInfoResponseContentIdRegExp).optional(),
  "totalTransactions": zod.number().optional(),
  "lastActivityAt": zod.number().optional()
})

export type GetWalletInfoResponseContent = zod.input<typeof GetWalletInfoResponseContent>;
export type GetWalletInfoResponseContentOutput = zod.output<typeof GetWalletInfoResponseContent>;
