/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mogtrade Economy
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const InternalServerErrorResponseContent = zod.object({
  "error": zod.string().describe('The error message from the server')
})

export type InternalServerErrorResponseContent = zod.input<typeof InternalServerErrorResponseContent>;
export type InternalServerErrorResponseContentOutput = zod.output<typeof InternalServerErrorResponseContent>;
