/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const CheckEmailAvailableParams = zod.object({
  "email": zod.string().describe('The email address query')
})

export type CheckEmailAvailableParams = zod.input<typeof CheckEmailAvailableParams>;
export type CheckEmailAvailableParamsOutput = zod.output<typeof CheckEmailAvailableParams>;
