/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const credentialSignUpRequestContentEmailRegExp = new RegExp('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$');
export const credentialSignUpRequestContentPasswordMin = 6;
export const credentialSignUpRequestContentPasswordMax = 100;

export const credentialSignUpRequestContentConfirmPasswordMin = 6;
export const credentialSignUpRequestContentConfirmPasswordMax = 100;


export const CredentialSignUpRequestContent = zod.object({
  "names": zod.string().describe('The names of the user'),
  "email": zod.string().regex(credentialSignUpRequestContentEmailRegExp).describe('The email address of the user. MUST be unique'),
  "password": zod.string().min(credentialSignUpRequestContentPasswordMin).max(credentialSignUpRequestContentPasswordMax).describe('User password'),
  "confirmPassword": zod.string().min(credentialSignUpRequestContentConfirmPasswordMin).max(credentialSignUpRequestContentConfirmPasswordMax).describe('Password confirmation. MUST have value equal to the password value')
})

export type CredentialSignUpRequestContent = zod.input<typeof CredentialSignUpRequestContent>;
export type CredentialSignUpRequestContentOutput = zod.output<typeof CredentialSignUpRequestContent>;
