/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const credentialSignUpBodyEmailRegExp = new RegExp('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$');
export const credentialSignUpBodyPasswordMin = 6;
export const credentialSignUpBodyPasswordMax = 100;

export const credentialSignUpBodyConfirmPasswordMin = 6;
export const credentialSignUpBodyConfirmPasswordMax = 100;


export const CredentialSignUpBody = zod.object({
  "names": zod.string().describe('The names of the user'),
  "email": zod.string().regex(credentialSignUpBodyEmailRegExp).describe('The email address of the user. MUST be unique'),
  "password": zod.string().min(credentialSignUpBodyPasswordMin).max(credentialSignUpBodyPasswordMax).describe('User password'),
  "confirmPassword": zod.string().min(credentialSignUpBodyConfirmPasswordMin).max(credentialSignUpBodyConfirmPasswordMax).describe('Password confirmation. MUST have value equal to the password value')
})

export type CredentialSignUpBody = zod.input<typeof CredentialSignUpBody>;
export type CredentialSignUpBodyOutput = zod.output<typeof CredentialSignUpBody>;
