/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const CredentialSignInResponseContent = zod.object({
  "accessToken": zod.string().describe('The access token (JWT) granted to the user'),
  "refreshToken": zod.string().describe('The refresh token')
})

export type CredentialSignInResponseContent = zod.input<typeof CredentialSignInResponseContent>;
export type CredentialSignInResponseContentOutput = zod.output<typeof CredentialSignInResponseContent>;
