/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const UnauthorizedErrorResponseContent = zod.object({
  "error": zod.string()
})

export type UnauthorizedErrorResponseContent = zod.input<typeof UnauthorizedErrorResponseContent>;
export type UnauthorizedErrorResponseContentOutput = zod.output<typeof UnauthorizedErrorResponseContent>;
