/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const ValidationErrorResponseContent = zod.object({
  "error": zod.array(zod.string()).describe('A list of validation messages')
})

export type ValidationErrorResponseContent = zod.input<typeof ValidationErrorResponseContent>;
export type ValidationErrorResponseContentOutput = zod.output<typeof ValidationErrorResponseContent>;
