/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import {
  CredentialSignInResponseContent,
  RotateAccessTokenResponseContent
} from '../../schemas';
import type {
  CredentialSignInRequestContent,
  CredentialSignInResponseContentOutput,
  CredentialSignUpRequestContent,
  RotateAccessTokenResponseContentOutput
} from '../../schemas';

import {
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';
import type {
  HttpHeaders
} from '@angular/common/http';

import {
  map
} from 'rxjs';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable()
export class MogTradeAuthenticationService {
  private readonly http = inject(HttpClient);
/**
 * This endpoint allows legitimate users to obtain a bearer JWT token and a corresponding refresh token
 */
 credentialSignIn(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientBodyOptions): Observable<CredentialSignInResponseContentOutput>;
 credentialSignIn(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientEventOptions): Observable<HttpEvent<CredentialSignInResponseContentOutput>>;
 credentialSignIn(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<CredentialSignInResponseContentOutput>>;
  credentialSignIn(
    credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientObserveOptions): Observable<CredentialSignInResponseContentOutput | HttpEvent<CredentialSignInResponseContentOutput> | AngularHttpResponse<CredentialSignInResponseContentOutput>> {
    if (options?.observe === 'events') {
      return this.http.post<CredentialSignInResponseContentOutput>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: CredentialSignInResponseContent.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.post<CredentialSignInResponseContentOutput>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    ).pipe(map(response => response.clone({ body: CredentialSignInResponseContent.parse(response.body) })));
    }

    return this.http.post<CredentialSignInResponseContentOutput>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    ).pipe(map(data => CredentialSignInResponseContent.parse(data)));
  }

/**
 * Rotate access token
 */
 rotateAccessToken( options?: HttpClientBodyOptions): Observable<RotateAccessTokenResponseContentOutput>;
 rotateAccessToken( options?: HttpClientEventOptions): Observable<HttpEvent<RotateAccessTokenResponseContentOutput>>;
 rotateAccessToken( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<RotateAccessTokenResponseContentOutput>>;
  rotateAccessToken(
     options?: HttpClientObserveOptions): Observable<RotateAccessTokenResponseContentOutput | HttpEvent<RotateAccessTokenResponseContentOutput> | AngularHttpResponse<RotateAccessTokenResponseContentOutput>> {
    if (options?.observe === 'events') {
      return this.http.get<RotateAccessTokenResponseContentOutput>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    ).pipe(map(event => event instanceof AngularHttpResponse ? event.clone({ body: RotateAccessTokenResponseContent.parse(event.body) }) : event));
    }

    if (options?.observe === 'response') {
      return this.http.get<RotateAccessTokenResponseContentOutput>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    ).pipe(map(response => response.clone({ body: RotateAccessTokenResponseContent.parse(response.body) })));
    }

    return this.http.get<RotateAccessTokenResponseContentOutput>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    ).pipe(map(data => RotateAccessTokenResponseContent.parse(data)));
  }

/**
 * Create user account using credentials
 */
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientBodyOptions): Observable<TData>;
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  credentialSignUp<TData = void>(
    credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

};
