/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MogTrade Authentication
 * OpenAPI spec version: 2026-02-09
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  CredentialSignInRequestContent,
  CredentialSignInResponseContent,
  CredentialSignUpRequestContent,
  RotateAccessTokenResponseContent
} from '../../schemas';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};







@Injectable()
export class MogTradeAuthenticationService {
  private readonly http = inject(HttpClient);
/**
 * This endpoint allows legitimate users to obtain a bearer JWT token and a corresponding refresh token
 */
 credentialSignIn<TData = CredentialSignInResponseContent>(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientBodyOptions): Observable<TData>;
 credentialSignIn<TData = CredentialSignInResponseContent>(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 credentialSignIn<TData = CredentialSignInResponseContent>(credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  credentialSignIn<TData = CredentialSignInResponseContent>(
    credentialSignInRequestContent: CredentialSignInRequestContent, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/auth/login/credential`,
      credentialSignInRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * Rotate access token
 */
 rotateAccessToken<TData = RotateAccessTokenResponseContent>( options?: HttpClientBodyOptions): Observable<TData>;
 rotateAccessToken<TData = RotateAccessTokenResponseContent>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 rotateAccessToken<TData = RotateAccessTokenResponseContent>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  rotateAccessToken<TData = RotateAccessTokenResponseContent>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/v1/auth/refresh`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

/**
 * Create user account using credentials
 */
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientBodyOptions): Observable<TData>;
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 credentialSignUp<TData = void>(credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  credentialSignUp<TData = void>(
    credentialSignUpRequestContent: CredentialSignUpRequestContent, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/api/v1/auth/register/credential`,
      credentialSignUpRequestContent,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

};
